src/posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import(
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	)

# urlpatterns = [
#     url(r'^$', post_list, name='list'),
# 	url(r'^create/$', post_create),
#     url(r'^(?P<id>\d+)/$', post_detail, name='detail'),
#     url(r'^(?P<id>\d+)/edit/$', post_update, name='update'),
#     url(r'^(?P<id>\d+)/delete/$', post_delete),

# ]

urlpatterns = [
    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
]

src/trydjango19/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin

from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^', include("posts.urls", namespace='posts')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils.safestring import mark_safe
from django.utils import timezone

from markdown_deux import markdown
from .utils import get_read_time


# Create your models here.

class PostManager(models.Manager):
	def active(self, *args, **kwargs):
		return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())



def upload_location(instance, filename):
	return "%s/%s" %(instance.id, filename)


class Post(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	title = models.CharField(max_length=120)
	slug = models.SlugField(unique=True)
	image = models.ImageField(upload_to=upload_location,
		null=True,
		blank=True,
		width_field="width_field",
		height_field="height_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	content = models.TextField()
	draft = models.BooleanField(default=False)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	read_time = models.IntegerField(default=0)#models.TimeField(null=True, blank=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)


	objects = PostManager()

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title
	
	def get_absolute_url(self):
		return reverse("posts:detail", kwargs={"slug": self.slug})

	class Meta:
		ordering = ['-timestamp', '-updated']

	def get_markdown(self):
		content = self.content
		markdown_text = markdown(content)
		return mark_safe(markdown_text)



def create_slug(instance, new_slug=None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Post.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug, qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)

	if instance.content:
		html_string = instance.get_markdown()
		read_time_var = get_read_time(html_string)
		instance.read_time = read_time_var



pre_save.connect(pre_save_post_receiver, sender=Post)

src/posts/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Post



class PostForm(forms.ModelForm):
	content=forms.CharField(widget=PagedownWidget(show_preview=False))
	publish = forms.DateField(widget=forms.SelectDateWidget)
	class Meta:
		model = Post
		fields = [
			"title",
			"content",
			"image",
			"draft",
			"publish",
		]

src/posts/views.py
from urllib.parse import quote_plus

from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import PostForm

from .models import Post





def post_create(request):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404


	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.user = request.user
		instance.save()
		messages.success(request, "Successfully created")
		return HttpResponseRedirect(instance.get_absolute_url())
	elif form.errors: #DIFFERENT FROM VIDEO WHICH SAID TO USE ELSE:
		messages.error(request, "Not successful")
	else:
		pass	
	context = {
		"form": form,
	}
	return render(request, "post_form.html", context)

def post_detail(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)
	if instance.publish > timezone.now().date():
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404
	share_string = quote_plus(instance.content)
	#share_string = quote(obj.content)﻿

	

	context={
		"title": instance.title,
		"instance": instance,
		"share_string": share_string,
	}
	return render(request, "post_detail.html", context)


def post_list(request):
	today = timezone.now().date()
	queryset_list =Post.objects.active() #.order_by('-timestamp')
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.all()

	query = request.GET.get("q")
	if query:
		queryset_list = queryset_list.filter(
			Q(title__icontains=query) |
			Q(content__icontains=query) |
			Q(user__first_name__icontains=query) |
			Q(user__last_name__icontains=query)
			).distinct()
	paginator = Paginator(queryset_list, 5) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)
	context = {
		"object_list": queryset,
		"title": "List",
		"page_request_var": page_request_var,
		"today": today,
	}
	return render(request, "post_list.html", context)



def post_update(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.save()
		messages.success(request, "Item Saved", extra_tags='html_safe')
		return HttpResponseRedirect(instance.get_absolute_url())
	context={
		"title": instance.title,
		"instance": instance,
		"form": form,
	}
	return render(request, "post_form.html", context)

def post_delete(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	instance.delete()
	messages.success(request, "Successfully deleted")
	return redirect("posts:list")

src/templates/base.html
{% load staticfiles %}
<!-- <!DOCTYPE html>
TESTING GIT -->

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Above - 3 meta tags per Bootstrap -->

	<title>{% block head_title %} Ramjee's Folly 3{% endblock %}</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">	

<link rel="stylesheet" href='{% static "/static/css/base.css" %}' />

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">


<style>
{% block style %} {% endblock style %}
</style>

{% block head_extra %} {% endblock head_extra %}

</head>
<body>


<!-- FACEBOOK COMMENTS - DELETED -->
<!-- <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.1&appId=655166147946693&autoLogAppEvents=1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script> -->

{% include "messages_display.html" %}
<div class='container'>
	<ol class = 'breadcrumb'>
		<li><a href='{% url "posts:list" %}'>Home</a></li>
		{% block post_detail_link %}
		{% endblock %}

		{% if request.user.is_authenticated %}
		<li class = 'pull-right'><a href='{% url "logout" %}'>Logout</a></li>
		<li class = 'pull-right'><a href=''>Welcome {{ user }}</a></li>
		{% else %}
		<li class = 'pull-right'><a href='{% url "login" %}'>Login</a></li>
		<li class = 'pull-right'><a href='{% url "register" %}'>Register</a></li>
		{% endif %}
	</ol>	



		
{% block content %}
{% endblock content %}
</div>

<script
  src="http://code.jquery.com/jquery-1.12.4.min.js"
  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>



<script type="text/javascript">
$(document).ready(function(){
	$(".content-markdown").each(function(){
			var content = $(this).text()
			var markedContent = marked(content)
			$(this).html(markedContent)
	})
	$(".post-detail-item img").each(function(){
			$(this).addClass("img-responsive")
	})

	
	var contentInput = $("#id_content");
	// $("#preview-content").html(marked(contentItem.val()))

	function setContent(value){
		var markedContent = marked(value)
		$("#preview-content").html(markedContent)
		$("#preview-content img").each(function(){
			$(this).addClass("img-responsive")
		})
	}

	setContent(contentInput.val())

	contentInput.keyup(function(){
		var newContent = $(this).val()
			setContent(newContent)
	})

	var titleInput = $("#id_title");

	function setTitle(value) {
		$("#preview-title").text(value)
	}

	setTitle(titleInput.val())

	titleInput.keyup(function(){
		var newContent = $(this).val()
			setTitle(newContent)

	})

	

})	
</script>

</body>
</html>

src/templates/messages_display.html
{% if messages %}
	<div class='messages'>
	<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if html_safe in message.tags %}{{ message|safe }}{% else %}{{message}}{% endif %}</li>
    {% endfor %}
	</ul>
	
	</div>
{% endif %}

src/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock %}

{% block post_detail_link %}
<li><a href='{{ instance.get_absolute_url }}'>{{ instance.title }}</a></li>
{% endblock %}


{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
	{% if instance.image %}
	<img src='{{ instance.image.url }}' class='img-responsive' />
	{% endif %}
<h1>{{ title }}<br/>
	<small>{% if instance.draft %}<span style='color: red'>Draft</span>
	{% endif %}{{ instance.publish }}</small></h1>
<p>Read time: {% if instance.read_time <= 1 %} < 1 min {% else %}{{ instance.read_time }} minutes{% endif %}</p>
{% if instance.user.get_full_name %}
<p class='byline'>Author: <strong>{{ instance.user.get_full_name }}</strong></p>
{% endif %}

<!-- FACEBOOK LIKE ABOVE POST  -->
<!-- <p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="false" data-share="false"></div></p>
<hr/> -->

<div class="row">
<div class='col-sm-12' >
<div class= 'post-detail-item'>{{ instance.get_markdown }}</div>
<!-- Story ID = {{ instance.id }} -->
<hr/>
<br/>

<!-- COMMENTS BOX BELOW POST -->
<!-- <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div> -->
</div>
</div>



<!-- <p><a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
Facebook
</a>

<a href="https://twitter.com/home?status={{ instance.content|truncatechars:20|urlify }}%20{{ request.build_absolute_uri}}">
Twitter
</a>

<a href='https://plus.google.com/share?url={{ request.build_absolute_uri}}'>Google+</a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri}}/&title=Be%20first%20%7C%20Join%20Swift%20for%20Entrepreneurs&summary=Swift%20for%20Entrepreneurs%20is%20a%20project-based%20programming%20course%20for%20non-technical%20founders.%20We'll%20learn%20how%20to%20build%20iOS%20apps%20from%20scratch%20using%20Apple's%20new%20programming%20language:%20Swift.%20Be%20first%20and%20learn%20with%20me!&source={{ request.build_absolute_uri}}">
Linkedin
</a>

<a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri}}&title=Unlock%20to%20Learn%20Swift%20for%20Free!%20By%20Swift%20for%20Entrepreneurs.%20Made%20for%20Non%20Techincals.">Reddit</a>
</p>
 -->
</div>

{% endblock content %}

</html>

src/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %}
{{ form.media }}

{% endblock head_extra %}


{% block content %}

<div class='col-sm-6'>
<h1>Preview</h1>
<div class='content preview'>
<h3 id='preview-title'></h3>
<p id='preview-content'></p>
</div>
</div>

<div class='col-sm-6'>


<h1>Form</h1>	

<form method="POST", action='' enctype='multipart/form-data'>{% csrf_token %}

{{ form|crispy }}

<input type='submit' class='btn btn-default' value='Create post' />


</form>

</div>

{% endblock content %}

src/templates/post_list.html
{% extends "base.html" %}

{% block content %}


<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ title }}</h1>
<form method="GET" action="" class="row">
    <div class="col-sm-6">
    <div class="input-group">
<input class="form-control" type="text" name="q" placeholder="Search posts" value="{{ request.GET.q }}" />
<span class="input-group-btn">
<!-- <input class="btn btn-default" type="submit" value="Search" /> -->
<button class="btn btn-default" type="submit"><i class="fas fa-search"></i></button>
</span>
</div>
    </div>
</form>

{% for obj in object_list %}

<div class="row">

<div class='row'>
  <div class="col-sm-12">
    <div class="thumbnail">
    	{% if obj.image %}
    	<img src='{{ obj.image.url }}' class='img-responsive' />
    	{% endif %}
      <div class="caption post-detail-item">
      	{% if obj.draft %}<h4>Draft</h4>{% endif%}{% if obj.publish > today %}<h4>Future post</h4>{% endif %}
        <h3><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a></h3>
            <p>{{ obj.publish }}| Est read time: {% if obj.read_time <= 1 %} < 1 min {% else %}{{ obj.read_time }} minutes{% endif %}</p>
        {% if obj.user.get_full_name %}
        <p>Author: {{ obj.user.get_full_name }}</p>
        {% endif %}
        {{ obj.get_markdown | truncatechars_html:120 }}
        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
      </div>
    </div>
  </div>
</div>

{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q'{{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q'{{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>

</div>

{% endblock content %}

src/templates/user_login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ title }}</h1>	
<hr/>


<form method="POST" action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='{{ title }}' />
</form>
</div>
{% endblock content %}